// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_TNoUgi-8eT_Ray6jA5z6p_V-Gsu_-Cg',
    appId: '1:479702107786:android:5aa465078fe33d3a09cf73',
    messagingSenderId: '479702107786',
    projectId: 'black-seed-app',
    storageBucket: 'black-seed-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2_PDWzrp1yFWWm6NXKd9YJJs_rF75N8',
    appId: '1:479702107786:ios:2c87bfde34db7ca209cf73',
    messagingSenderId: '479702107786',
    projectId: 'black-seed-app',
    storageBucket: 'black-seed-app.firebasestorage.app',
    androidClientId: '479702107786-vr26ijcdaori8pvtoa5ponemsocko2cc.apps.googleusercontent.com',
    iosClientId: '479702107786-vjil8bb2i0uil4b0jg1pfjmrfel21tu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackSeed',
  );

}